adding RESUMEHERE marker

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -14,11 +14,15 @@ ag 'tap>' <(echo $staged_changes | ag '^\+') \
     && echo "[pre-commit/ERROR]: Found calls to tap>!" >&2 \
     && exit 13
 
+ag 'RESUMEHERE' <(echo $staged_changes | ag '^\+') \
+    && echo "[pre-commit/ERROR]: Found RESUMEHERE markers!" >&2 \
+    && exit 14
+
 local markers="$(echo $staged_changes | ag '^\+' | ag 'TASK')"
 if [[ -n "$markers" ]]; then
     echo "[pre-commit/ERROR]: Found staged TASK markers:"
     echo $markers
-    exit 14
+    exit 15
 fi
 
 git flow config &> /dev/null \
@@ -30,7 +34,7 @@ git flow config &> /dev/null \
 #if [[ -n "$markers" ]]; then
 #    echo "[pre-commit/ERROR]: Found TASK markers in branch:"
 #    echo $markers
-#    exit 15
+#    exit 16
 #fi
 
 if [[ `cmds list` =~ 'pre_commit' ]]; then
